version: "3.9"

services:
  scheduler-app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app  # Enables hot reload for development
    networks:
      - backend

networks:
  backend:
